#pragma once
#include "vec.h"
#include "mat4.h"

#define v2plus , v2a ,
#define v2plusf , v2af ,
#define fplusv2 , fav2 ,
#define v2mul , v2m ,
#define v2mulf , v2mf ,
#define fmulv2 , fmv2 ,
#define v2div , v2d ,
#define v2divf , v2df ,
#define fdivv2 , fdv2 ,
#define v2minus , v2s ,
#define v2minusf , v2sf ,
#define fminusv2 , fsv2 ,

#define v3plus , v3a ,
#define v3plusf , v3af ,
#define fplusv3 , fav3 ,
#define v3mul , v3m ,
#define v3mulf , v3mf ,
#define fmulv3 , fmv3 ,
#define v3div , v3d ,
#define v3divf , v3df ,
#define fdivv3 , fdv3 ,
#define v3minus , v3s ,
#define v3minusf , v3sf ,
#define fminusv3 , fsv3 ,

#define v4plus , v4a ,
#define v4plusf , v4af ,
#define fplusv4 , fav4 ,
#define v4mul , v4m ,
#define v4mulf , v4mf ,
#define fmulv4 , fmv4 ,
#define v4div , v4d ,
#define v4divf , v4df ,
#define fdivv4 , fdv4 ,
#define v4minus , v4s ,
#define v4minusf , v4sf ,
#define fminusv4 , fsv4 ,

#define m2plus , m2a ,
#define m2plusf , m2af ,
#define fplusm2 , fam2 ,
#define m2mulv2 , m2mv2 ,
#define m2mul , m2m ,
#define m2mulf , m2mf ,
#define fmulm2 , fmm2 ,
#define m2minus , m2s ,
#define m2minusf , m2sf ,
#define fminusm2 , fsm2 ,
#define m2divf , m2df ,

#define m3plus , m3a ,
#define m3plusf , m3af ,
#define fplusm3 , fam3 ,
#define m3mulv3 , m3mv3 ,
#define m3mul , m3m ,
#define m3mulf , m3mf ,
#define fmulm3 , fmm3 ,
#define m3minus , m3s ,
#define m3minusf , m3sf ,
#define fminusm3 , fsm3 ,
#define m3divf , m3df ,

#define m4plus , m4a ,
#define m4plusf , m4af ,
#define fplusm4 , fam4 ,
#define m4mulv4 , m4mv4 ,
#define m4mul , m4m ,
#define m4mulf , m4mf ,
#define fmulm4 , fmm4 ,
#define m4minus , m4s ,
#define m4minusf , m4sf ,
#define fminusm4 , fsm4 ,
#define m4divf , m4df ,